name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2

      - name: Sync with Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.4
        with:
          github_repo_id: Akshayalnyn/google-guardian-ai
          huggingface_repo_id: Akshayalnyn/Guardian-AI
          repo_type: space
          space_sdk: streamlit
          hf_token: ${{ secrets.HF_TOKEN }}
